# text file with all the bigsi indexes (use absolute paths)
indexes: /home/leandro/git/BIGSI/snakemake/index.txt

# fasta file with sequences to be searched in the indexes
fasta: /home/leandro/git/BIGSI/snakemake/fasta.txt

# where to put results (final results will be in a file "result.json" in this dir)
output_dir: bigsi_search_out

# bigsi kmer presence threshold
threshold: 1.0

# singularity img with bigsi to be called
singularity_img: /home/leandro/git/BIGSI/containers/docker/sing_image/leandroishilima_bigsi_700k_0.0.1-2020-02-20-f2cc0916be9a.simg

# cache for each bigsi index (increasing cache can speed up searching, but the job takes longer to be scheduled)
cache_mem_gb: 2
